name: Release

on:
  workflow_call:
    secrets:
      OPM_PUBLISH_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04
    container: openresty/openresty:1.21.4.1-0-focal
    env:
      OPM_PUBLISH_TOKEN: ${{ secrets.OPM_PUBLISH_TOKEN }}
    steps:
      - name: Install git
        run: apt-get update && apt-get install -y git
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Fix for issue brought up here: https://github.com/actions/checkout/issues/1169
      - name: Git config workaround
        run: git config --global --add safe.directory /__w/lua-resty-gcs-signature/lua-resty-gcs-signature
      - name: Setup SVU
        id: svu
        uses: obfu5c8/action-svu@v1.0.0
        with:
          strip-prefix: true
          svu-version: 2.2.0
      - name: Create git tag
        run: git tag ${{ steps.svu.outputs.version }}
      - name: Push tag to origin
        run: git push origin ${{ steps.svu.outputs.version }}
      - name: Build
        run: make VERSION=${{ steps.svu.outputs.version }} populate_opmrc publish
      - name: Generate changelog
        id: git-cliff
        uses: orhun/git-cliff-action@v3.0.2
        with:
          args: --latest --strip all
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.svu.outputs.version }}
          name: Release ${{ steps.svu.outputs.version }}
          body: ${{ steps.git-cliff.outputs.content }}
          artifacts: lua-resty-gcs-signature-${{ steps.svu.outputs.version }}.tar.gz
